version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    rebase-strategy: disabled
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly
